version: '3.8'

services:
  app:
    image: ohsingh/bgrm:0.0.1
    restart: always
    environment:
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - R2_ENDPOINT_URL=${R2_ENDPOINT_URL}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_REGION_NAME=${R2_REGION_NAME}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
    networks:
      - backend
    ports:
      - 5002:5002

  worker:
    image: ohsingh/bgrm:0.0.1
    restart: always
    command: celery -A main.celery worker --loglevel=info --concurrency=4 --pool=gevent -Q paid,free
    environment:
      - REDIS_URL=${REDIS_URL}
      - R2_ENDPOINT_URL=${R2_ENDPOINT_URL}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_REGION_NAME=${R2_REGION_NAME}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:


